name: Build images

on:
  push:
    branches:
      - "main"
jobs:
  build_images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ART_USR }}
          password: ${{ secrets.ART_PWD }}
      - name: Get short SHA
        id: short_sha
        run: echo "short_sha=$(echo ${{ github.sha }} | cut -c1-6)" >> $GITHUB_ENV
      - name: Build and push
        run: |
           docker build -t minhquan0107/spark-demo:${{ env.short_sha }} .
           docker push minhquan0107/spark-demo:${{ env.short_sha }}